package com.example.interactivemap.logic.service;

public interface LocationBroadcastData {
    int BROADCAST_LOCATION_DATA = 1;
    int BROADCAST_LOCATION_PROVIDERS_STATE = 2;
    int BROADCAST_LOCATION_PROVIDERS_STATE_GPS_ON = 2000;
    int BROADCAST_LOCATION_PROVIDERS_STATE_GPS_OFF = 2001;
    int BROADCAST_LOCATION_PROVIDERS_STATE_NET_ON = 2002;
    int BROADCAST_LOCATION_PROVIDERS_STATE_NET_OFF = 2003;
}
